### ISSUE TITLE
Scheduling UI: more guidance around scheduling new actions:

### ISSUE THREAD

**Issue by attaboy** [ellipsis-ai/ellipsis#3000]
- [x] make it possible to schedule new actions by name — resolved by #3001 
- [x] if by trigger, show which action will be run, ~and then allow setting input values~ — resolved by #3002 
- [x] setting input values should use the question text, not the input name, and not be open-ended -- resolved by #3048
